version: '3'
services:
  auth:
    build: ./auth-api
    ports:
      - '8000:3000'
    environment:
      TOKEN_KEY: 'shouldbeverysecure'
  users:
    build: ./users-api
    ports:
      - '8080:3000'
    environment:
      MONGODB_CONNECTION_URI: 'mongodb://mongo:27017/users?retryWrites=true&w=majority'
      AUTH_API_ADDRESS: 'auth:3000'
    depends_on:
      - mongo
  tasks:
    build: ./tasks-api
    ports:
      - '3000:3000'
    environment:
      MONGODB_CONNECTION_URI: 'mongodb://mongo:27017/users?retryWrites=true&w=majority'
      AUTH_API_ADDRESS: 'auth:3000'
    depends_on:
      - mongo
  mongo:
    image: mongo
