apiVersion: v1
kind: Service
metadata:
  name: second-service
  labels:
    group: example
spec:
  selector:
    app: second-app
    tier: backend
  ports:
    - protocol: TCP
      name: second-node
      port: 80
      targetPort: 8080
    # - protocol: 'TCP'
    #   name: 'third-node'
    #   port: 8081
    #   targetPort: 8081
  type: LoadBalancer
